class Paciente {
    - nome: String
    - cpf: String
    - nascimento: Date

    + cadastrar()
    + atualizarDados()
}

class Consulta {
    - data: Date
    - medico: String

    + agendar()
}

Paciente --> Consulta
